name: carbon_footprint_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^8.1.0
  gap: 
  flutter_animate: 
  fl_chart: 
  percent_indicator:
  convert:
  flutter_expandable_fab:
  hive: 
  hive_flutter: 
  path_provider: 
  email_validator:
  username_validator:
  air_quality:
  geolocator:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600